project_name: tmux-githop

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/tmux-githop
    binary: tmux-githop
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - license: MIT
    maintainer: Callum
    homepage: https://github.com/callumio/tmux-githop
    description: A CLI tool that integrates tmux with ghq to provide an interactive way to hop between your Git repositories and tmux sessions.
    formats:
      - deb
      - rpm
      - apk
    dependencies:
      - tmux
    recommends:
      - ghq

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  github:
    owner: callumio
    name: tmux-githop